"""
Integration test configuration and utilities.
"""

import pytest
import os
from pathlib import Path


def pytest_configure(config):
    """Configure pytest for integration tests."""
    # Check if API key is available
    api_key = os.environ.get('Z_AI_API_KEY')
    if not api_key or api_key in ['your_api_key_here', 'test123', '']:
        print("\n" + "="*70)
        print("WARNING: Z_AI_API_KEY not set or is a placeholder")
        print("Integration tests will be skipped.")
        print("Set the environment variable to run integration tests:")
        print("  export Z_AI_API_KEY=your_actual_key")
        print("="*70 + "\n")


def cleanup_test_files(module_name: str):
    """Clean up files created during test runs."""
    patterns = [
        f"{module_name}.py",
        f"test_{module_name}.py",
        ".coverage",
        "htmlcov"
    ]
    
    for pattern in patterns:
        for f in Path('.').rglob(pattern):
            try:
                if f.is_file():
                    f.unlink()
                elif f.is_dir():
                    import shutil
                    shutil.rmtree(f)
            except Exception:
                pass


def find_run_files(run_dir: str) -> dict:
    """Find files generated by a brick run."""
    run_path = Path(run_dir)
    
    return {
        'reports': list(run_path.glob('*_report.txt')),
        'halted_reports': list(run_path.glob('*_halted_report.txt')),
        'ui_files': list(run_path.glob('*_ui.html')),
        'runner_files': list(run_path.glob('*_runner.py')),
        'state_files': list(run_path.glob('*.json'))
    }


@pytest.fixture
def integration_test_specs_dir():
    """Path to integration test spec files."""
    return Path(__file__).parent / "specs"


@pytest.fixture
def simple_math_spec():
    """Simple math spec for testing."""
    return {
        "module_name": "simple_math_test",
        "module_description": "Simple math for testing",
        "required_public_functions": [
            {
                "name": "add",
                "description": "Add two numbers",
                "inputs": ["a: float", "b: float"],
                "outputs": "float",
                "side_effects": "None"
            }
        ]
    }


@pytest.fixture
def temp_runs_dir(tmp_path):
    """Temporary directory for run files."""
    runs_dir = tmp_path / "runs"
    runs_dir.mkdir()
    return str(runs_dir)
